// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///
/// ```
//import 'package:firebase_core/firebase_core.dart';

// ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZtS59GW5CYXpq6MHjN7PFxLCj_tEF_Vc',
    appId: '1:720509869942:web:0e786590f0350567e8a457',
    messagingSenderId: '720509869942',
    projectId: 'reuse-b7524',
    authDomain: 'reuse-b7524.firebaseapp.com',
    storageBucket: 'reuse-b7524.appspot.com',
    measurementId: 'G-S4470KD6DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHBzk7XSj2xDb6zAZGkQ-EVv-wARucuig',
    appId: '1:720509869942:android:e708bc90c6904faae8a457',
    messagingSenderId: '720509869942',
    projectId: 'reuse-b7524',
    storageBucket: 'reuse-b7524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37v-DM5WVszNGmpO5To163au4aVflu6M',
    appId: '1:720509869942:ios:0add650fc94c2495e8a457',
    messagingSenderId: '720509869942',
    projectId: 'reuse-b7524',
    storageBucket: 'reuse-b7524.appspot.com',
    iosClientId:
        '720509869942-ctip02re5qog79ffjncgvh8gvkr5p021.apps.googleusercontent.com',
    iosBundleId: 'com.example.reuseapp',
  );
}
